imports:
    - { resource: config.yml }

framework:
    assets:
        version: %version%

monolog:
    handlers:
        main:
            type:  rotating_file
            path: '%kernel.logs_dir%/%kernel.environment%.log'
            action_level: error
            level: debug
            max_files: 10
            channels: ['!event']