parameters:
    ovh_api_cks:
        GET: %ovh_api_ck_get%
        POST: %ovh_api_ck_post%
        DELETE: %ovh_api_ck_delete%
        PUT: %ovh_api_ck_put%

services:
    ovh_api_service:
        abstract: true
        class: AppBundle\Service\OvhApiService
        arguments: 
          - '%ovh_api_url%'
          - '%ovh_api_ak%'
          - '%ovh_api_as%'
          - '%ovh_api_cks%'
          
    app.api_service:
        parent: ovh_api_service
        class: AppBundle\Service\ApiService
        calls:
          - [setZoneName, ['%ovh_zone_name%']]
          - [setLogger, ['@logger']]