parameters:

services:
    ## App services
    app.google_api:
        abstract: true
        class: AppBundle\Service\Api\GoogleApi
        arguments: 
          - '%google_api_endpoint%'
          - '%google_api_key%'
          
    app.google_service:
        parent: app.google_api
        class: AppBundle\Service\GoogleService
        calls:
          - [setLogger, ['@logger']]
          
    app.prayer_times_service:
        class: AppBundle\Service\PrayerTimeService
          
    app.form_configuration:
        class: AppBundle\Form\ConfigurationType
        arguments:
            - "@app.google_service"
            - "@translator"
        tags:
            - { name: form.type }          
            
    app.form_prayer:
        class: AppBundle\Form\PrayerType
        arguments:
            - "@translator"
        tags:
            - { name: form.type }          
    
    ## Tiers services
    gedmo.listener.sluggable:
        class: Gedmo\Sluggable\SluggableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]
            
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
        calls:
            - [ setAnnotationReader, [ "@annotation_reader" ] ]    