AppBundle\Entity\User:
    properties:
        plainPassword:
            - Regex: 
                pattern: '/(?=.*[a-z])(?=.*[A-Z])(?=.*\d)[a-zA-Z\d]{8,}/'
                message: "form.registration.wrong_password_message"              
                groups: [appChangePassword]

AppBundle\Entity\Mosque:
    properties:
        city:
            - NotBlank: ~
            
AppBundle\Entity\Configuration:
    properties:
        hadithLang:
            - Choice: {callback : "getHadithLangs"}