AppBundle\Entity\Configuration:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\ConfigurationRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lang:
            type: string
            length: 255
        jumuaTime:
            type: string
            length: 255
            nullable: true
        aidTime:
            type: string
            length: 255
            nullable: true
        imsakNbMinBeforeFajr:
            type: smallint
            nullable: true
        maximumIshaTimeForNoWaiting:
            type: string
            length: 255
            nullable: true
        waitingTimes:
            type: simple_array
        adjustedTimes:
            type: simple_array
            nullable: true
        fixedTimes:
            type: simple_array
            nullable: true
        hijriAdjustment:
            type: smallint
        hijriDateEnabled:
            type: boolean
        duaAfterAzanEnabled:
            type: boolean
        duaAfterPrayerEnabled:
            type: boolean
        androidAppEnabled:
            type: boolean
        sourceCalcul:
            type: string
            length: 255
        prayerMethod:
            type: string
            length: 255
            nullable: true
        latitude:
            type: float
            nullable: true
        longitude:
            type: float
            nullable: true            
        fajrDegree:
            type: smallint
            nullable: true
        ishaDegree:
            type: smallint
            nullable: true
        iqamaDisplayTime:
            type: smallint
        azanDuaDisplayTime:
            type: smallint
        created:
            type: datetime
            gedmo:
                timestampable:
                    on: create  
        updated:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
            
    lifecycleCallbacks: {  }
