AppBundle\Entity\Message:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MessageRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
            nullable: true
        content:
            type: text
        enabled:
            type: boolean
        delay:
            type: integer
    manyToOne:
        mosque:
            targetEntity: AppBundle\Entity\Mosque
            inversedBy: messages
            joinColumn:
                name: mosque_id
                referencedColumnName: id
                onDelete: CASCADE             
    lifecycleCallbacks: {  }
