AppBundle\Entity\Mosque:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\MosqueRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 1024
        associationName:
            type: string
            length: 255
            nullable: true
        slug:
            type: string
            length: 255
            unique: true
            gedmo:
                slug:
                  separator: "-"
                  updatable: true
                  fields:
                    - name    
                    - city    
        phone:
            type: string
            length: 255
            nullable: true
        email:
            type: string
            length: 255
            nullable: true
        address:
            type: string
            length: 1024
            nullable: true
        city:
            type: string
            length: 255
            nullable: true
        country:
            type: string
            length: 255
            nullable: true
        zipcode:
            type: string
            length: 255
            nullable: true
        rib:
            type: string
            length: 1024
            nullable: true
        site:
            type: string
            length: 255
            nullable: true            
        created:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: create            
        updated:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                name: user_id
                referencedColumnName: id
                onDelete: CASCADE            
    oneToOne:
        configuration:
            targetEntity: AppBundle\Entity\Configuration
            mappedBy: mosque

    lifecycleCallbacks: {  }
