AppBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: AppBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        tou:
          type: boolean
          groups: [ "Registration" ]
        created:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: create
        updated:
            type: datetime
            nullable: true
            gedmo:
                timestampable:
                    on: update
    oneToMany:
        mosques:
            targetEntity: AppBundle\Entity\Mosque
            mappedBy: user