AppBundle\Entity\Mosque:
    justificatoryFile:
        mapping:           file
        filename_property: justificatory
    file1:
        mapping:           file
        filename_property: image1
    file2:
        mapping:           file
        filename_property: image2
    file3:
        mapping:           file
        filename_property: image3