AppBundle\Entity\Mosque:
    file1:
        mapping:           mosque_image
        filename_property: image1
    file2:
        mapping:           mosque_image
        filename_property: image2
    file3:
        mapping:           mosque_image
        filename_property: image3